FROM common AS base
ADD . .

FROM base AS build
ENV PCSC_LIB_NAME=static=pcsclite
RUN <<-EOF
	set -eux
	env -C apps/reshard/provision cargo build ${CARGOFLAGS}
	cp /target/${TARGET}/release/reshard_provision /
	file /reshard_provision | grep "static-pie"
EOF

FROM base AS install
WORKDIR /rootfs
COPY --from=build /reshard_provision .
RUN find . -exec touch -hcd "@0" "{}" +

FROM scratch AS package
COPY --from=install /rootfs .
ENTRYPOINT ["/reshard_provision"]
