FROM common AS build
ADD . .

RUN pkg-config --modversion libpcsclite

# Directory for Rust artifacts
ENV RELEASE_DIR=/target/x86_64-unknown-linux-musl/release

ENV PCSC_LIB_NAME=static=pcsclite
RUN --network=none cargo build ${CARGOFLAGS} --package reshard_provision

RUN mkdir -p /rootfs/
RUN cp target/x86_64-unknown-linux-musl/release/reshard_provision /rootfs/
RUN file /rootfs/reshard_provision| grep "static-pie"

FROM scratch AS package
COPY --from=build /rootfs/. .
