name: "Set up Docker"
description: "Ensure Docker is configured correctly"
inputs:
  ghcr:
    description: "Github API key"
    required: false
runs:
  using: "composite"
  steps:
    - name: Setup and configure docker
      shell: 'script -q -e -c "bash {0}"'
      run: |
        [[ $EUID -ne 0 ]] && exec sudo /bin/sh "$0" "$@"
        docker version

        cat << EOF >/etc/docker/daemon.json
        {
          "features": {
          "containerd-snapshotter": true
          },
          "registry-mirrors": ["https://ghcr.io/tkhq"]
        }
        EOF

        systemctl restart docker
        docker buildx create --driver docker-container --bootstrap --name build --use

    - name: Login to GHCR
      shell: 'script -q -e -c "bash {0}"'
      run: |
        echo "${{ inputs.ghcr }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
