[package]
name = "codegen"
edition = "2021"
version = "0.1.0"

[workspace]

[dependencies]
tonic-prost-build = { version = "0.14", features = ["transport", "cleanup-markdown"], default-features = false }
