FROM stagex/pallet-rust:sx2025.06.0@sha256:740b9ed5f2a897d45cafdc806976d84231aa50a64998610750b42a48f8daacab AS build

# Rust configuration
ENV RUSTFLAGS='-C target-feature=+crt-static'
ENV CARGOFLAGS='--target x86_64-unknown-linux-musl --no-default-features --locked --release'

# Directory for Rust artifacts
ENV RELEASE_DIR=/target/x86_64-unknown-linux-musl/release

# Load Rust sources
ADD . .

# pre-fetch all workspace deps; we need to them to build with `--network=none` later
RUN cargo fetch

WORKDIR /apps/reshard/host
RUN --network=none <<-EOF
    set -eu
    cargo build ${CARGOFLAGS} --features vsock
    mkdir -p /rootfs/usr/local/bin
    mv ${RELEASE_DIR}/reshard_host /rootfs/usr/local/bin/
    ln -s /usr/local/bin/reshard_host /rootfs/reshard_host.linux-x86_64
EOF

FROM scratch AS package
COPY --from=build /rootfs/. .
